examples/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Low Revenue</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

examples/main/default/classes/ZTestBR_InactiveAccount.cls
@isTest
public with sharing class ZTestBR_InactiveAccount {

    @isTest
    public static void testValidExecute() {
        Account validAccount = new Account(
            Is_Active__c = false
        );
        Account oldAccount = new Account(
            Is_Active__c = true
        );
        Test.startTest();
        BR_InactiveAccount testRule = new BR_InactiveAccount(validAccount, oldAccount);
        testRule.process();
        Test.stopTest();

        Assert.areEqual('Inactive', validAccount.Status__c, 'Account should have inactive status');
    }

    @isTest
    public static void testInvalidExecute() {
        Account validAccount = new Account(
            Is_Active__c = false
        );
        Account oldAccount = new Account(
            Is_Active__c = true
        );
        Test.startTest();
        BR_InactiveAccount testRule = new BR_InactiveAccount(validAccount, oldAccount);
        testRule.process();
        Test.stopTest();

        Assert.areEqual('Inactive', validAccount.Status__c, 'Account should have inactive status');
    }

    @isTest
    public static void testInvalidExecute2() {
        Account validAccount = new Account(
            Is_Active__c = false
        );
        Test.startTest();
        BR_InactiveAccount testRule = new BR_InactiveAccount(validAccount, null);
        testRule.process();
        Test.stopTest();

        Assert.areEqual('Inactive', validAccount.Status__c, 'Account should have inactive status');
    }
}