examples/main/default/objects/Account/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Low Revenue</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

examples/main/default/classes/BR_InactiveAccount.cls
public with sharing class BR_InactiveAccount extends BR_AbstractAccountStatus{


    public BR_InactiveAccount (Account newAccount, Account oldAccount) {
        super(newAccount, oldAccount);

        nextRule = new BR_LowRevenueAccount(newAccount, oldAccount);
    }

    
    public override Boolean shouldExecute() {
        return !newAccount.Is_Active__c && oldAccount != null && oldAccount.Is_Active__c;
    }

    public override void execute() {
        newAccount.Status__c = 'Inactive';
    }

}